version: "3"
services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    container_name: postgres-policia
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
